Repository prgrms-web-devcourse/Team_CherryBoys_MatchUs_FE, pull requests merged in 2021-12, with the labels that each got.

#13 feat: 팀원 상세보기 페이지 구현(MAT-103)
  src/api/index.ts
  src/api/team.ts
  src/components/TeamPlayerManage/MemberList/MemberList.tsx
  src/components/TeamPlayerManage/MemberList/MemberListElements.tsx
  src/components/TeamPlayerManage/MemberList/memberList.module.scss
  src/components/TeamPlayerManage/index.ts
  src/components/index.ts
  src/pages/TeamMemberManage/TeamMemberManage.tsx
  src/pages/TeamMemberManage/teamMemberManage.module.scss
  src/pages/index.ts
Labels: 리뷰 반영 완료

#12 feat: 팀 상세보기 페이지 (MAT-41)
  src/api/core.ts
  src/api/team.ts
  src/pages/TeamDetail/TeamDetail.tsx
  src/pages/TeamDetail/teamDetail.module.scss
  src/utils/api.ts
  src/utils/index.ts
Labels: 리뷰 반영 완료

#17 feat: 매치 상세페이지(MAT-152)
  package.json
  public/index.html
  src/components/MatchDetail/MatchListElement/MatchElement.tsx
  src/components/MatchDetail/MatchListElement/index.ts
  src/components/MatchDetail/index.ts
  src/pages/MatchDetail/MatchDetail.tsx
  src/pages/MatchDetail/matchDetail.module.scss
  src/styles/_color.scss
  src/styles/_common.scss
  src/styles/_reset.scss
  yarn.lock
Labels: 리뷰 반영 완료

#15 refactor: 헤더, 탭바 로직 통일 및 스타일린트 적용
  src/App.tsx
  src/components/DefaultTemplate/DefaultTemplate.tsx
  src/components/common/Header/Header.module.scss
  src/components/common/Header/Header.tsx
  src/components/common/Inputs/Input/Input.tsx
  src/components/common/TabBar/TabBar.module.scss
  src/components/common/TabBar/TabBar.tsx
  src/components/index.ts
Labels: 리뷰 반영 완료

#21 refactor: axios return data를 response.data.data로 변경
  src/api/core.ts
Labels: 리뷰 반영 완료

#25 feat: not found page(MAT-170)
  src/assets/images/errorIcon.png
  src/pages/NotFound/NotFound.tsx
  src/pages/NotFound/notFound.module.scss
  src/styles/_color.scss
Labels: 리뷰 반영 완료

#27 feat: route path를 적용하여 컴포넌트 라우팅 (MAT-173)
  src/Router/Router.tsx
  src/consts/routes.js
  src/pages/HiresAccept/HiresAccept.tsx
  src/pages/HiresCreate/HiresCreate.tsx
  src/pages/HiresDetail/HiresDetail.tsx
  src/pages/HiresEdit/HiresEdit.tsx
  src/pages/HiresFilter/HiresFilter.tsx
Labels: 리뷰 요청

#5 feat: 용병(및 매치) 리스트 페이지 마크업 작성
  src/App.tsx
  src/components/Post/PostItem/PostItem.tsx
  src/components/Post/PostItem/postItem.module.scss
  src/components/Post/Posts/Posts.tsx
  src/components/Post/Posts/posts.module.scss
  src/components/Post/index.ts
  src/components/index.ts
  src/fixtures/hireItems.ts
  src/fixtures/matchItems.ts
  src/index.tsx
  src/pages/HiresPage.tsx
  src/pages/MatchesPage.tsx
  src/pages/index.ts
  src/store/index.ts
  src/store/posts/index.ts
  yarn.lock
Labels: 리뷰 반영 완료

#30 feat: 팀 페이지 라우터 주소 추가
  src/Router/Router.tsx
  src/pages/index.ts
Labels: 리뷰 반영 완료

#20 feat: 팀 하위 페이지에 API 연결(MAT-163)
  src/api/core.ts
  src/api/team.ts
  src/components/TeamPlayerManage/MemberList/MemberList.tsx
  src/components/index.ts
  src/hooks/useForm.ts
  src/pages/MatchDetail/MatchDetail.tsx
  src/pages/TeamCreate/TeamCreate.tsx
  src/pages/TeamDetail/TeamDetail.tsx
  src/pages/TeamInfoEdit/TeamInfoEdit.tsx
  src/pages/TeamMemberManage/TeamMemberManage.tsx
  src/types/Team/Team.ts
  src/types/index.ts
  src/utils/validation/validation.ts
Labels: 리뷰 요청, 용스톤

#19 feat: 매칭 등록 페이지 추가 (MAT-111)
  package.json
  src/Router/Router.tsx
  src/components/Match/MatchPosts/MatchPosts.tsx
  src/consts/routes.js
  src/dummyMatch.ts
  src/pages/NewMatch/NewMatch.module.scss
  src/pages/NewMatch/NewMatchPage.tsx
  src/pages/index.ts
  yarn.lock
Labels: 리뷰 반영 완료, 시즈

#31 feat: route path를 적용하여 컴포넌트 라우팅 재PR (MAT-173)
  src/Router/Router.tsx
  src/pages/Hires/Hires.tsx
  src/pages/HiresPage.tsx
  src/pages/index.ts
Labels: 개발 진행 중

#22 feat: 회원가입 페이지 기능 구현 (MAT-99)
  src/api/auth.ts
  src/consts/signup.ts
  src/pages/Signup/Signup.tsx
  src/pages/Signup/ValidInput.tsx
  src/store/authSlice.ts
  src/types/auth.ts
  src/utils/validation/signupValidation.ts
Labels: 리뷰 요청, 시즈, 용스톤

#14 feat: 용병 상세페이지 (MAT-57)
  src/Router/AuthorizedRoute.tsx
  src/Router/Router.tsx
  src/pages/HiresDetail/HiresDetail.tsx
  src/pages/HiresDetail/hiresDetail.module.scss
Labels: 리뷰 반영 완료

#33 feat: 팀 페이지 라우팅 연결 (MAT-195)
  src/Router/Router.tsx
  src/pages/MatchDetail/MatchDetail.tsx
  src/pages/TeamDetail/TeamDetail.tsx
  src/pages/index.ts
Labels: 리뷰 요청, 체리, 쭝, 용스톤

#29 feat: 로그인 페이지 추가(MAT-50)
  src/App.tsx
  src/api/auth.ts
  src/api/core.ts
  src/pages/Login/Login.tsx
  src/pages/Signup/Signup.tsx
  src/store/authSlice.ts
  src/store/index.ts
  src/types/auths.ts
Labels: 리뷰 요청, 시즈, 쭝, 용스톤

#34 feat: 팀원 관리 API 연결 (MAT-196)
  src/api/team.ts
  src/components/TeamPlayerManage/MemberList/MemberList.tsx
  src/pages/TeamMemberManage/TeamMemberManage.tsx
Labels: 리뷰 요청, 체리, 쭝, 용스톤

#32 feat: 공통 모달 컴포넌트 (MAT-171)
  public/index.html
  src/components/common/CustomModalDialog/CustomModalDialog.tsx
  src/components/common/CustomModalDialog/customModalDialog.module.scss
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/modal.module.scss
  src/components/common/Portal/Portal.tsx
  src/components/common/index.ts
Labels: 리뷰 요청, 체리

#37 feat: 팀 관련 API 연동 (MAT-196)
  src/api/team.ts
  src/components/TeamPlayerManage/MemberList/MemberList.tsx
  src/components/TeamPlayerManage/MemberList/MemberListElements.tsx
  src/components/common/CustomModalDialog/CustomModalDialog.tsx
  src/pages/TeamCreate/TeamCreate.tsx
  src/pages/TeamDetail/TeamDetail.tsx
  src/pages/TeamMemberManage/TeamMemberManage.tsx
  src/pages/TeamMemberManage/teamMemberManage.module.scss
  src/store/authSlice.ts
  src/types/Team/Team.ts
  tsconfig.json
Labels: 리뷰 반영 완료

#35 feat: 매칭 리스트 필터 기능 추가(MAT-138)
  src/components/Match/MatchListFilterModal/MatchListFilterModal.module.scss
  src/components/Match/MatchListFilterModal/MatchListFilterModal.tsx
  src/components/Match/MatchPosts/MatchPosts.tsx
  src/components/Match/index.ts
  src/components/common/Inputs/Input/Input.tsx
  src/consts/info.ts
  src/store/match/match.ts
  src/types/match.ts
Labels: 리뷰 반영 완료

#36 feat: 팀원 정보 수정 기능 분리 구현(MAT-197)
  src/components/Match/MatchTeamMemberModal/MatchTeamMemberModal.module.scss
  src/components/Match/MatchTeamMemberModal/MatchTeamMemberModal.tsx
  src/components/Match/TeamCard/TeamCard.module.scss
  src/components/Match/TeamCard/TeamCard.tsx
  src/components/Match/index.ts
  src/components/common/Inputs/InputCheckBox/InputCheckBox.module.scss
  src/components/common/Inputs/InputCheckBox/InputCheckBox.tsx
  src/consts/info.ts
  src/pages/EditMatch/EditMatchPage.tsx
  src/pages/Match/MatchPage.tsx
  src/pages/NewMatch/NewMatchPage.tsx
  src/store/match/match.ts
  src/types/match.ts
Labels: 리뷰 반영 완료

#40 feat: 유저 상세페이지 구현(MAT-218)
  src/Router/Router.tsx
  src/api/user.ts
  src/pages/TeamMatchDetail/TeamMatchDetail.tsx
  src/pages/TeamMatchDetail/teamMatchDetail.module.scss
  src/pages/UserDetail/UserDetail.tsx
  src/pages/index.ts
Labels: 리뷰 요청, 체리

#39 feat: 팀 선택 페이지 구현 (MAT-208)
  src/components/TeamPlayerManage/MemberList/MemberList.tsx
  src/pages/TeamChoice/TeamChoice.tsx
  src/pages/TeamChoice/TeamInfoCard.tsx
  src/pages/TeamChoice/teamChoice.module.scss
  src/pages/TeamDetail/TeamDetail.tsx
  src/pages/TeamDetail/teamDetail.module.scss
  src/types/Team/Team.ts
Labels: 리뷰 요청, 체리

#41 feat: 유저 매치 상세페이지 추가
  src/api/user.ts
  src/pages/UserMatchDetail/UserMatchDetail.tsx
  src/pages/UserMatchDetail/userMatchDetail.module.scss
Labels: 리뷰 요청, 체리

#42 feat: 매칭 API 연결 (MAT-145)
  src/api/index.ts
  src/api/match.ts
  src/components/Match/MatchApplyModal/MatchApplyModal.tsx
  src/components/Match/MatchApproveModal/MatchApproveModal.module.scss
  src/components/Match/MatchApproveModal/MatchApproveModal.tsx
  src/components/Match/MatchDetail/MatchDetail.tsx
  src/components/Match/MatchInfo/MatchInfo.tsx
  src/components/Match/MatchListFilterModal/MatchListFilterModal.tsx
  src/components/Match/MatchPostCard/MatchPostCard.tsx
  src/components/Match/MatchPosts/MatchPosts.module.scss
  src/components/Match/MatchPosts/MatchPosts.tsx
  src/components/Match/MatchReviewModal/MatchReviewModal.tsx
  src/components/Match/MatchTeamMemberModal/MatchTeamMemberModal.tsx
  src/components/Match/TeamCard/TeamCard.module.scss
  src/components/Match/TeamCard/TeamCard.tsx
  src/components/Match/index.ts
  src/components/common/Header/Header.module.scss
  src/components/common/Inputs/Input/Input.tsx
  src/dummyMatch.ts
  src/pages/EditMatch/EditMatchPage.tsx
  src/pages/HiresDetail/HiresDetail.tsx
  src/pages/Match/MatchPage.tsx
  src/pages/Matches/MatchesPage.tsx
  src/pages/NewMatch/NewMatchPage.tsx
  src/store/match/match.ts
  src/types/Match/Match.ts
  src/types/index.ts
Labels: 리뷰 반영 완료

#38 feat: 용병관련 API 데이터 전송 및 수신 성공(MAT-184)
  src/api/hires.ts
  src/pages/Hires/Hires.tsx
  src/pages/HiresAccept/HiresAccept.tsx
  src/pages/HiresCreate/HiresCreate.tsx
  src/pages/HiresDetail/HiresDetail.tsx
  src/pages/HiresEdit/HiresEdit.tsx
Labels: 리뷰 반영 완료

#24 feat: 용병, 매칭 리스트 페이지의 필터 마크업 구현(MAT-172)
  src/consts/info.ts
  src/pages/HiresFilter/HiresFilter.tsx
Labels: 리뷰 요청

#43 feat: 유저 수정 페이지 구현 및 ReduxSlice 수정 (MAT-180)
  src/App.tsx
  src/Router/Router.tsx
  src/api/auth.ts
  src/api/core.ts
  src/api/index.ts
  src/api/user.ts
  src/components/common/CustomInput/CustomInput.tsx
  src/consts/user.ts
  src/pages/Login/Login.tsx
  src/pages/Signup/Signup.tsx
  src/pages/Signup/ValidInput.tsx
  src/pages/TeamMatchDetail/TeamMatchDetail.tsx
  src/pages/UserInfoEdit/UserInfoEdit.tsx
  src/store/authSlice.ts
  src/store/index.ts
  src/store/userSlice.ts
  src/types/auth.ts
  src/types/users.ts
  src/utils/validation/userValidation.ts
  src/utils/validation/validation.ts
Labels: 리뷰 반영 완료

#48 refactor: baseUrl 변경
  src/api/core.ts
Labels: 리뷰 반영 완료

#57 chore: package.lock file 제거
  package-lock.json
Labels: 긴급 🚀

#54 feat: 용병 수락페이지 마크업 및 토글 기능 (MAT-120)
  src/components/Applications/ApplicationElement/ApplicationElement.tsx
  src/components/Applications/index.ts
  src/pages/HiresAccept/HiresAccept.tsx
Labels: 리뷰 요청, 시즈, 용스톤

#55 refactor: 용병 등록에서 포지션, 연령대, 장소를 컴포넌트화, 필터 마크업 및 기능, 용병 수정페이지 마크업 및 기능(MAT-116, MAT-234)
  src/Router/Router.tsx
  src/api/hires.ts
  src/components/selects/AgeGroup.tsx
  src/components/selects/Date.tsx
  src/components/selects/HiresPosition.tsx
  src/components/selects/Place.tsx
  src/components/selects/index.ts
  src/pages/HiresCreate/HiresCreate.tsx
  src/pages/HiresDetail/HiresDetail.tsx
  src/pages/HiresEdit/HiresEdit.tsx
  src/pages/HiresFilter/HiresFilter.tsx
Labels: 리뷰 요청

#60 refactor: 용병 리스트에서 api에서 받은 용병 신청글로 뷰에 출력, 신청글 누르면 상세페이지 이동 (MAT-232)
  src/components/Post/PostItem/PostItem.tsx
  src/components/Post/Posts/Posts.tsx
  src/pages/Hires/Hires.tsx
  src/store/posts/index.ts
Labels: 리뷰 요청

#62 feat: 설정 페이지 추가 (MAT-244)
  src/Router/Router.tsx
  src/pages/Setting/Setting.module.scss
  src/pages/Setting/Setting.tsx
Labels: 리뷰 요청, 시즈

#51 refactor: Header에 로그인 상태에 따른 렌더링 추가 (MAT-231)
  src/components/common/Header/Header.tsx
  src/store/userSlice.ts
Labels: 리뷰 요청, 시즈, 쭝, 용스톤

#52 refactor: 라우터 순서 재배열 및 Authorized 컴포넌트 적용 (MAT-233)
  src/Router/AuthorizedRoute.tsx
  src/Router/Router.tsx
  src/consts/routes.js
Labels: 리뷰 요청, 시즈, 쭝, 용스톤

#50 feat: location api call로직 추가(mat 221)
  src/api/match.ts
  src/components/Match/MatchListFilterModal/MatchListFilterModal.tsx
  src/pages/EditMatch/EditMatchPage.tsx
  src/pages/NewMatch/NewMatchPage.tsx
  src/store/match/match.ts
  src/types/Match/Match.ts
Labels: 리뷰 반영 완료

#64 feat: 용병 리스트 페이지 스타일링
  src/components/Post/PostItem/PostItem.tsx
  src/components/Post/Posts/Posts.tsx
Labels: 리뷰 요청, 시즈

#53 refactor: 컴포넌트 수정 및 로그인 페이지 스타일링(MAT-237)
  src/assets/images/logo.png
  src/components/common/CustomModalDialog/CustomModalDialog.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/login.module.scss
Labels: 리뷰 요청, 시즈, 용스톤

#61 feat: 매치 상세보기 스타일링 (MAT-249)
  src/components/MatchDetail/MatchListElement/MatchListElement.tsx
  src/components/MatchDetail/MatchListElement/matchListElement.module.scss
  src/pages/TeamDetail/TeamDetail.tsx
  src/pages/TeamMatchDetail/TeamMatchDetail.tsx
  src/pages/TeamMatchDetail/teamMatchDetail.module.scss
  src/pages/UserDetail/UserDetail.tsx
  src/pages/UserMatchDetail/UserMatchDetail.tsx
  src/pages/UserMatchDetail/userMatchDetail.module.scss
Labels: 리뷰 반영 완료

#56 refactor: 유저 정보 수정 페이지 스타일 추가 및 검증 추가 (MAT-238)
  src/pages/Signup/Signup.tsx
  src/pages/Signup/ValidInput.tsx
  src/pages/UserInfoEdit/UserInfoEdit.tsx
  src/pages/UserInfoEdit/userInfoEdit.module.scss
  src/utils/validation/userValidation.ts
Labels: 리뷰 요청, 용스톤

#58 refactor: 스타일 추가 및 중복확인 오류 수정 (MAT-243)
  src/pages/Signup/Signup.tsx
  src/pages/Signup/signup.module.scss
Labels: 리뷰 요청

#59 feat: 매칭 평가 기능 추가 및 권한체크 로직 추가(MAT-201, MAT-222)
  src/api/match.ts
  src/components/Match/MatchApplyModal/MatchApplyModal.tsx
  src/components/Match/MatchApproveModal/MatchApproveModal.tsx
  src/components/Match/MatchButton/MatchButton.tsx
  src/components/Match/MatchDetail/MatchDetail.module.scss
  src/components/Match/MatchDetail/MatchDetail.tsx
  src/components/Match/MatchPosts/MatchPosts.tsx
  src/components/Match/MatchReviewModal/MatchReviewModal.tsx
  src/components/Match/MatchTeamMemberModal/MatchTeamMemberModal.tsx
  src/components/Match/TeamCard/TeamCard.tsx
  src/pages/EditMatch/EditMatchPage.tsx
  src/pages/Match/MatchPage.tsx
  src/pages/NewMatch/NewMatchPage.tsx
  src/store/match/match.ts
  src/types/Match/Match.ts
Labels: 리뷰 요청

#65 feat: 팀 초대 리스트 페이지 추가 (MAT-246)
  src/api/user.ts
  src/pages/UserTeamInvitation/UserTeamInvitation.tsx
  src/pages/UserTeamInvitation/userTeamInvitation.module.scss
  src/store/userSlice.ts
Labels: 리뷰 요청, 시즈

#68 fix: 에러 수정
  src/Router/Router.tsx
  src/api/user.ts
  src/pages/Login/Login.tsx
  src/pages/Signup/Signup.tsx
  src/pages/UserInfoEdit/UserInfoEdit.tsx
  src/pages/UserTeamInvitation/UserTeamInvitation.tsx
  src/pages/index.ts
  src/store/userSlice.ts
Labels: 리뷰 요청

#69 refactor: 타입 순환 린트 오류 해결
  src/Router/Router.tsx
  src/pages/HiresCreate/HiresCreate.tsx
  src/pages/HiresDetail/HiresDetail.tsx
  src/pages/HiresEdit/HiresEdit.tsx
  src/pages/index.ts
  src/types/Hires/Hires.ts
  src/types/index.ts
Labels: 긴급 🚀

#73 refactor: 팀 생성 & 수정 페이지 스타일링(MAT-251)
  src/components/common/CustomInput/CustomInput.tsx
  src/hooks/useForm.ts
  src/pages/TeamCreate/TeamCreate.tsx
  src/pages/TeamCreate/teamCreate.module.scss
  src/pages/TeamInfoEdit/TeamInfoEdit.tsx
Labels: 리뷰 요청, 용스톤

#74 feat: 용병 생성 페이지에서 사용자 입력에 따라 서버에 요청, 완료후 용병 리스트 페이지로 이동 (MAT-262)
  src/components/selects/LocationSelect.tsx
  src/components/selects/index.ts
  src/pages/HiresCreate/HiresCreate.tsx
Labels: 리뷰 요청

#72 refactor: 유저 상세페이지 스타일링(MAT-259)
  src/components/MatchDetail/MatchListElement/MatchListElement.tsx
  src/components/MatchDetail/MatchListElement/matchListElement.module.scss
  src/pages/UserDetail/UserDetail.tsx
  src/pages/UserDetail/userDetail.module.scss
  src/pages/UserMatchDetail/UserMatchDetail.tsx
Labels: 리뷰 요청, 용스톤

#71 fix: Header 로그인버튼 클릭시 메인이 아닌 로그엔 페이지로 가도록 수정 (MAT-258)
  src/components/common/Header/Header.tsx
Labels: 리뷰 요청, 용스톤

#77 refactor: 용병 구인글 생성, 수정 페이지 css 수정(MAT-267)
  src/components/selects/AgeGroup.tsx
  src/components/selects/LocationSelect.tsx
  src/components/selects/select.module.scss
  src/pages/HiresCreate/HiresCreate.module.scss
  src/pages/HiresCreate/HiresCreate.tsx
Labels: 리뷰 요청

#81 refactor: 용병 필터 스타일 수정 (MAT-267)
  src/components/Applications/ApplicationElement/ApplicationElement.module.scss
  src/components/Applications/ApplicationElement/ApplicationElement.tsx
  src/components/Match/MatchApplyModal/MatchApplyModal.module.scss
  src/components/Match/MatchApproveModal/MatchApproveModal.module.scss
  src/components/Match/MatchDetail/MatchDetail.module.scss
  src/components/Match/MatchDetail/MatchDetail.tsx
  src/components/Match/MatchPosts/MatchPosts.module.scss
  src/components/Match/MatchReviewModal/MatchReviewModal.module.scss
  src/components/Match/MatchTeamMemberModal/MatchTeamMemberModal.module.scss
  src/components/Post/Posts/Posts.tsx
  src/components/index.ts
  src/pages/EditMatch/EditMatch.module.scss
  src/pages/HiresAccept/HiresAccept.tsx
  src/pages/HiresCreate/HiresCreate.module.scss
  src/pages/HiresDetail/HiresDetail.tsx
  src/pages/HiresDetail/hiresDetail.module.scss
  src/pages/HiresFilter/HiresFilter.module.scss
  src/pages/HiresFilter/HiresFilter.tsx
  src/pages/NewMatch/NewMatch.module.scss
Labels: 리뷰 요청

#75 refactor: 팀 상세보기 페이지 스타일링 (MAT-263 & 264)
  package.json
  src/components/MatchDetail/MatchListElement/MatchListElement.tsx
  src/components/TeamPlayerManage/MemberList/MemberList.tsx
  src/components/TeamPlayerManage/MemberList/MemberListElements.tsx
  src/components/TeamPlayerManage/MemberList/memberList.module.scss
  src/pages/TeamDetail/TeamDetail.tsx
  src/pages/TeamDetail/teamDetail.module.scss
  src/pages/TeamMemberManage/TeamMemberManage.tsx
  src/pages/TeamMemberManage/teamMemberManage.module.scss
  yarn.lock
Labels: 리뷰 요청

#76 style: 메인 페이지 스타일링 (MAT-265)
  src/api/hires.ts
  src/pages/Hires/Hires.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/main.module.scss
  src/store/match/match.ts
  src/store/posts/index.ts
Labels: 리뷰 요청, 개발 진행 중

#78 style: login page 반응형 추가 및 로고 에러 수정(MAT-268)
  src/assets/images/logo.png
  src/pages/Login/Login.tsx
  src/pages/Login/login.module.scss
Labels: 리뷰 요청, 쭝, 용스톤

#84 refactor: 용병 필터 스타일 수정(MAT-267)
  src/components/Applications/ApplicationElement/ApplicationElement.module.scss
  src/pages/HiresDetail/HiresDetail.tsx
  src/pages/HiresFilter/HiresFilter.module.scss
  src/pages/HiresFilter/HiresFilter.tsx
Labels: 리뷰 요청

#83 refactor: 매칭 관련 스토어 및 스타일 수정(MAT-272)
  src/components/Match/MatchApplyModal/MatchApplyModal.module.scss
  src/components/Match/MatchApproveModal/MatchApproveModal.module.scss
  src/components/Match/MatchDetail/MatchDetail.module.scss
  src/components/Match/MatchInfo/MatchInfo.module.scss
  src/components/Match/MatchListFilterModal/MatchListFilterModal.module.scss
  src/components/Match/MatchPostCard/MatchPostCard.module.scss
  src/components/Match/MatchPosts/MatchPosts.module.scss
  src/components/Match/MatchReviewModal/MatchReviewModal.module.scss
  src/components/Match/MatchTeamMemberModal/MatchTeamMemberModal.module.scss
  src/components/Match/TeamCard/TeamCard.module.scss
  src/components/Match/TeamCard/TeamCard.tsx
  src/pages/EditMatch/EditMatch.module.scss
  src/pages/Match/Match.module.scss
  src/pages/Match/MatchPage.tsx
  src/pages/NewMatch/NewMatch.module.scss
  src/store/match/match.ts
Labels: 리뷰 요청, 시즈

#82 refactor: 통합 후 발생하는 key 에러 제거 (MAT-271)
  src/components/TeamPlayerManage/MemberList/MemberList.tsx
  src/pages/Main/Main.tsx
  src/pages/TeamChoice/TeamInfoCard.tsx
  src/pages/TeamDetail/TeamDetail.tsx
  src/pages/UserDetail/UserDetail.tsx
Labels: 리뷰 요청, 쭝, 용스톤

#79 feat: 용병 글 삭제, 용병 신청, 수락 구현완료, 남은것 우선순위 정리 (MAT-266)
  README.md
  src/api/hires.ts
  src/components/Applications/ApplicationElement/ApplicationElement.module.scss
  src/components/Applications/ApplicationElement/ApplicationElement.tsx
  src/components/Match/MatchApplyModal/MatchApplyModal.module.scss
  src/components/Match/MatchDetail/MatchDetail.module.scss
  src/components/Match/MatchDetail/MatchDetail.tsx
  src/components/Match/MatchInfo/MatchInfo.module.scss
  src/components/Match/MatchListFilterModal/MatchListFilterModal.module.scss
  src/components/Match/MatchTeamMemberModal/MatchTeamMemberModal.module.scss
  src/components/Match/TeamCard/TeamCard.module.scss
  src/components/Post/PostItem/PostItem.tsx
  src/components/Post/PostItem/postItem.module.scss
  src/components/Post/Posts/Posts.tsx
  src/components/Post/Posts/posts.module.scss
  src/components/common/Header/Header.module.scss
  src/components/index.ts
  src/components/selects/HiresPosition.tsx
  src/pages/EditMatch/EditMatch.module.scss
  src/pages/Hires/Hires.tsx
  src/pages/HiresAccept/HiresAccept.tsx
  src/pages/HiresCreate/HiresCreate.module.scss
  src/pages/HiresCreate/HiresCreate.tsx
  src/pages/HiresDetail/HiresDetail.tsx
  src/pages/HiresDetail/hiresDetail.module.scss
  src/pages/HiresFilter/HiresFilter.module.scss
  src/pages/HiresFilter/HiresFilter.tsx
  src/pages/Match/Match.module.scss
  src/store/posts/index.ts
  src/types/Hires/Hires.ts
Labels: 개발 진행 중

#87 refactor: QA 중 css 수정(MAT-273)
  src/components/Match/MatchPostCard/MatchPostCard.module.scss
  src/components/Match/TeamCard/TeamCard.module.scss
  src/components/common/Header/Header.module.scss
  src/components/common/TabBar/TabBar.module.scss
  src/components/common/TabBar/TabBar.tsx
  src/pages/Match/Match.module.scss
  src/pages/TeamChoice/TeamChoice.tsx
  src/pages/TeamChoice/teamChoice.module.scss
  src/pages/UserDetail/userDetail.module.scss
Labels: 리뷰 요청

#86 chore: _redirects 파일 추가 (MAT-275)
  public/_redirects
Labels: 긴급 🚀

#91 fix: 팀 멤버가 렌더링 안되는 에러 정정
  src/components/TeamPlayerManage/MemberList/MemberList.tsx
  src/pages/TeamChoice/TeamChoice.tsx
  src/pages/TeamChoice/teamChoice.module.scss
Labels: 긴급 🚀

#100 chore: netlify.toml 파일 추가
  netlify.toml
Labels: 긴급 🚀

#104 refactor: 매칭 평가api 수정(MAT-273)
  src/api/match.ts
Labels: 긴급 🚀

#105 refactor: 매칭 생성,수정 시간 관련 이슈 해결
  src/components/common/AttitudeTag/attitudeTag.module.scss
  src/components/common/TabBar/TabBar.tsx
  src/pages/EditMatch/EditMatchPage.tsx
  src/pages/NewMatch/NewMatchPage.tsx
Labels: 긴급 🚀

#106 fix: 용병 생성시 시간 validation 보완, 장소와 팀 미선택시 모달 오류 개선 (MAT-286)
  src/pages/HiresCreate/HiresCreate.tsx
  src/pages/Login/login.module.scss
  src/pages/TeamCreate/TeamCreate.tsx
  src/pages/TeamCreate/teamCreate.module.scss
  src/pages/TeamDetail/teamDetail.module.scss
Labels: 긴급 🚀

#107 refactor: 팀 상세페이지 개선
  src/pages/TeamDetail/TeamDetail.tsx
Labels: 리뷰 요청, 용스톤

#113 hotfix: fix duplicated check response key name
  src/pages/Signup/Signup.tsx
Labels: 긴급 🚀
